
---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/afia
    username: afia_user
    password: afia
---
spring:
  jpa:
    hibernate.ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
      jpa:
         properties:
                   hibernate:
                            format_sql: true
---
spring:
       datasource:
                 initialization-mode: always

---


spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: afia.sql
